In [30]:
# Customer Lifetime Value (CLTV) Analysis

In [31]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option("display.max_columns", None)

In [32]:
df = pd.read_csv("cleaned_retail_sales.csv")

df["transaction_date"] = pd.to_datetime(df["transaction_date"])

df.head()

,transaction_id,transaction_date,customer_id,customer_gender,customer_age_group,customer_segment,product_id,product_name,category,brand,quantity,unit_price,discount_pct,sales_amount,payment_method,sales_channel,region,year,month,month_name,quarter,day,day_name
0,T0000001,2024-04-24,C000820,Other,35-44,Returning,P1082,Dumbbells,Sports,Brand 1,2,313.53,20,501.65,Debit Card,Online,North,2024,4,April,2,24,Wednesday
1,T0000002,2025-07-12,C002849,Other,45-54,New,P1087,Running Shoes,Sports,Brand 3,1,366.16,0,366.16,Credit Card,Online,South,2025,7,July,3,12,Saturday
2,T0000003,2025-06-01,C019727,Male,55+,Returning,P1030,Sneakers,Clothing,Brand 3,1,27.99,0,27.99,Gift Card,In-Store,South,2025,6,June,2,1,Sunday
3,T0000004,2025-08-26,C009116,Male,25-34,VIP,P1058,Sunscreen,Beauty,Brand 1,2,102.01,15,173.42,Cash,In-Store,South,2025,8,August,3,26,Tuesday
4,T0000005,2024-12-10,C003350,Male,45-54,New,P1028,Sneakers,Clothing,Brand 1,1,259.55,0,259.55,Cash,In-Store,Central,2024,12,December,4,10,Tuesday

In [33]:
purchase_frequency = df.groupby("customer_id").size().reset_index(name="PurchaseFrequency")

purchase_frequency.head()

  customer_id  PurchaseFrequency
0     C000001                  4
1     C000002                  6
2     C000003                  4
3     C000004                  4
4     C000005                  3

In [34]:
customer_metrics = df.groupby("customer_id").agg(
    TotalRevenue=("sales_amount", "sum"),
    TotalOrders=("transaction_id", "count")
).reset_index()

customer_metrics.head()

  customer_id  TotalRevenue  TotalOrders
0     C000001       1401.11            4
1     C000002       1330.54            6
2     C000003       1349.69            4
3     C000004       2597.00            4
4     C000005        720.48            3

In [35]:
purchase_frequency = df.groupby("customer_id").size().reset_index(name="PurchaseFrequency")

purchase_frequency.head()

  customer_id  PurchaseFrequency
0     C000001                  4
1     C000002                  6
2     C000003                  4
3     C000004                  4
4     C000005                  3

In [36]:
purchase_frequency = df.groupby("customer_id").size().reset_index(name="PurchaseFrequency")

purchase_frequency.head()

  customer_id  PurchaseFrequency
0     C000001                  4
1     C000002                  6
2     C000003                  4
3     C000004                  4
4     C000005                  3

In [37]:
purchase_frequency = df.groupby("customer_id").size().reset_index(name="PurchaseFrequency")

purchase_frequency.head()

  customer_id  PurchaseFrequency
0     C000001                  4
1     C000002                  6
2     C000003                  4
3     C000004                  4
4     C000005                  3

In [38]:
customer_metrics = customer_metrics.merge(
    purchase_frequency,
    on="customer_id"
)

customer_metrics.head()

  customer_id  TotalRevenue  TotalOrders  PurchaseFrequency
0     C000001       1401.11            4                  4
1     C000002       1330.54            6                  6
2     C000003       1349.69            4                  4
3     C000004       2597.00            4                  4
4     C000005        720.48            3                  3

In [39]:
customer_metrics = customer_metrics.merge(
    purchase_frequency,
    on="customer_id"
)

customer_metrics.head()

,customer_id,TotalRevenue,TotalOrders,PurchaseFrequency_x,PurchaseFrequency_y
0,C000001,1401.11,4,4,4
1,C000002,1330.54,6,6,6
2,C000003,1349.69,4,4,4
3,C000004,2597.00,4,4,4
4,C000005,720.48,3,3,3

In [40]:
customer_metrics = customer_metrics.merge(
    purchase_frequency,
    on="customer_id"
)

customer_metrics.head()

,customer_id,TotalRevenue,TotalOrders,PurchaseFrequency_x,PurchaseFrequency_y,PurchaseFrequency
0,C000001,1401.11,4,4,4,4
1,C000002,1330.54,6,6,6,6
2,C000003,1349.69,4,4,4,4
3,C000004,2597.00,4,4,4,4
4,C000005,720.48,3,3,3,3

In [41]:
customer_metrics.describe()

,TotalRevenue,TotalOrders,PurchaseFrequency_x,PurchaseFrequency_y,PurchaseFrequency
count,24784.000000,24784.000000,24784.000000,24784.000000,24784.000000
mean,1830.094192,4.841833,4.841833,4.841833,4.841833
std,1127.568802,2.159686,2.159686,2.159686,2.159686
min,6.570000,1.000000,1.000000,1.000000,1.000000
25%,978.190000,3.000000,3.000000,3.000000,3.000000
50%,1640.400000,5.000000,5.000000,5.000000,5.000000
75%,2488.087500,6.000000,6.000000,6.000000,6.000000
max,8788.670000,15.000000,15.000000,15.000000,15.000000

In [44]:
customer_metrics['AOV'] = (
    customer_metrics['TotalRevenue']
    / customer_metrics['TotalOrders']
)

In [45]:
customer_metrics['AOV'] = (
    customer_metrics['TotalRevenue']
    / customer_metrics['TotalOrders']
)

In [46]:
customer_metrics['AOV'] = (
    customer_metrics['TotalRevenue']
    / customer_metrics['TotalOrders']
)

In [51]:
top_customers = customer_metrics.sort_values(
    "CLTV",
    ascending=False
).head(10)

top_customers

,customer_id,TotalRevenue,TotalOrders,PurchaseFrequency_x,PurchaseFrequency_y,PurchaseFrequency,AOV,CLTV
1488,C001502,8788.67,13,13,13,13,676.051538,8788.67
12989,C013102,8401.58,11,11,11,11,763.780000,8401.58
9328,C009405,7993.31,13,13,13,13,614.870000,7993.31
24004,C024216,7840.01,11,11,11,11,712.728182,7840.01
347,C000351,7808.19,14,14,14,14,557.727857,7808.19
21274,C021457,7550.32,10,10,10,10,755.032000,7550.32
10415,C010502,7533.87,12,12,12,12,627.822500,7533.87
11001,C011095,7366.26,9,9,9,9,818.473333,7366.26
22752,C022957,7309.62,11,11,11,11,664.510909,7309.62
14123,C014242,7234.36,12,12,12,12,602.863333,7234.36

In [52]:
top_customers = customer_metrics.sort_values(
    "CLTV",
    ascending=False
).head(10)

top_customers

,customer_id,TotalRevenue,TotalOrders,PurchaseFrequency_x,PurchaseFrequency_y,PurchaseFrequency,AOV,CLTV
1488,C001502,8788.67,13,13,13,13,676.051538,8788.67
12989,C013102,8401.58,11,11,11,11,763.780000,8401.58
9328,C009405,7993.31,13,13,13,13,614.870000,7993.31
24004,C024216,7840.01,11,11,11,11,712.728182,7840.01
347,C000351,7808.19,14,14,14,14,557.727857,7808.19
21274,C021457,7550.32,10,10,10,10,755.032000,7550.32
10415,C010502,7533.87,12,12,12,12,627.822500,7533.87
11001,C011095,7366.26,9,9,9,9,818.473333,7366.26
22752,C022957,7309.62,11,11,11,11,664.510909,7309.62
14123,C014242,7234.36,12,12,12,12,602.863333,7234.36